export const masterDescriptors = {
  Generator: `Generators are confident, outspoken and clear about what they want. They are focused on achieving measurable outcomes and go all out to get the job done. They are quick decision makers, risk takers and love a challenge. Goal oriented, they'll be interested in results and are excellent at galvanising others to deliver against a target. Setting high standards for themselves, they expect nothing less from others and this can be hard for people who have a different dominant preference. Generators tend to like working with people who share their drive for success and thrive off the shared energy this provides. Their desire to win makes them tough negotiators and they quickly lose interest where there's no end goal in sight.`,
  
  Reflector: `If you want a job done right, a Reflector is the person to ask. They are super organised and brilliant at designing and following processes that give them the outcome they expect. Detail focused, they like clear information and will seek out data to guide and validate their choices. Reflectors thrive in self-led situations where they have the autonomy to determine their own course of action. They use what they know to make rational rather than emotional decisions and prefer to have time to think about their options before signing on the dotted line. Reflectors like to be around people who communicate clearly and openly and find it harder to be with people who are overtly emotional.`,
  
  Connector: `Connectors have a very strong empathy streak, they look out for others and seek to build good relationships with the people around them. Always friendly and loyal, they enjoy initiating conversations and love building a sense of camaraderie with people who share their values. They make decisions based on emotional connection and are happiest where they feel a bond of mutual trust and respect has been formed. Sometimes less strident about their own ability, Connectors enjoy being part of a wider team or venture. They are often attracted to more assertive people who create the successful outcomes they are less confident in driving themselves. Connectors do not respond well to people who appear to lack concern or empathy for others.`,
  
  Ignitor: `Ignitors carry an overflowing cup. They are energetic, look for positives and can see the silver lining in almost every situation. They love throwing ideas around and use lateral thinking to move things on to the next stage. Typically visual thinkers, they 'get' the big picture and are always happy to be involved in new things with endless possibilities. Quick to see potential, they thrive on working with others to develop their thinking. On the flip side, they disengage when they lose interest or if momentum starts to wane. Great team workers, Ignitors bring energy and positivity to group situations and often inspire others to share and contribute. They love being around people with a similar outlook and tend to struggle with those they consider to be mood hoovers. Planning and organisation are not notable Ignitor qualities.`
}

export const pressureStatements = {
  Generator: `BE MINDFUL UNDER PRESSURE: Your drive for measurable outcomes can make you appear impatient; you may become a tough negotiator who shuts down without a clear win.`,
  
  Reflector: `BE MINDFUL UNDER PRESSURE: Your need for facts can make you appear cold; you may struggle to decide if you feel you lack complete information.`,
  
  Connector: `BE MINDFUL UNDER PRESSURE: Your desire for harmony can lead you to avoid necessary conflict, you may become less strident about your own abilities and wait for others to lead.`,
  
  Ignitor: `BE MINDFUL UNDER PRESSURE: Your big-picture thinking can turn into a lack of focus; you may disengage the moment a project requires detailed planning or momentum slows.`
}
