export const masterDescriptors = {
  Generator: `Generators are confident, outspoken and clear about what they want. They are focused on achieving measurable outcomes and go all out to get the job done. They are quick decision makers, risk takers and love a challenge. Goal oriented, they'll be interested in results and are excellent at galvanising others to deliver against a target. Setting high standards for themselves, they expect nothing less from others and this can be hard for people who have a different dominant preference. Generators tend to like working with people who share their direct communication style and decisive nature.`,
  
  Reflector: `Reflectors are thoughtful, analytical and considered. They like to explore options and will do their homework before making a decision. They're good at seeing the bigger picture and working with stakeholders from different perspectives. They often keep their thoughts to themselves and can come across as reserved, but they're actually absorbing a lot of information. Reflectors bring balance and depth to decision-making processes. They prefer to work with people who appreciate their thorough approach and give them time to think things through.`,
  
  Connector: `Connectors are people-focused and natural communicators. They are genuinely interested in others and build strong relationships. They're excellent networkers and enjoy bringing people together. They're good listeners and often act as the glue in teams, helping people understand each other. Connectors care deeply about how decisions impact people and are often the ones championing culture and team morale. They prefer collaborative working environments where relationships are valued and there's open communication.`,
  
  Ignitor: `Ignitors are energetic, enthusiastic and creative. They bring excitement and new ideas to the table and love exploring possibilities and imagining what could be. They're natural innovators who see potential where others don't. They often jump between ideas quickly and can seem unfocused to those with different preferences. Ignitors are passionate about their vision and are excellent at inspiring and motivating others around big possibilities. They thrive in environments that encourage experimentation and value creative thinking.`
}
